language: php

services:
  - memcached

php: [7.0, 7.1]

before_script:
  - composer install --prefer-source --no-interaction --no-progress --ignore-platform-reqs

script:
  - bin/phpspec run -f pretty --no-interaction