--- 
- name: Prepare basic env for php apps on all nodes
  hosts: staging-http
  become: yes
  become_method: sudo
  vars_files:
      - vars/project.yml
  roles:
    - tools
    - apache
    - php7.0
    - project