--- 
- name: Prepare basic env for php apps on all nodes
  hosts: vagrant-db
  remote_user: vagrant
  connection: local
  become: yes
  become_method: sudo
  vars_files:
        - vars/project.yml
        - vars/mysql.yml
  roles:
    - mysql