---
- name: Download Composer installer
  get_url: url=https://getcomposer.org/installer dest=/usr/local/bin/composer-setup.php

- name: Install Composer
  shell: php /usr/local/bin/composer-setup.php --install-dir=/usr/local/bin

- name: Setup Composer
  copy: src=/usr/local/bin/composer.phar dest=/usr/local/bin/composer mode=0755

- name: Remove composer.phar
  file: path="/usr/local/bin/composer.phar" state=absent

- name: Remove Composer installer
  file: path="/usr/local/bin/composer-setup.php" state=absent