imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: parameters.php }

framework:
    secret: '%secret_key%'
    form: ~
    assets: ~
    templating:
        engines: ['twig']
    serializer:
        enabled: true
        enable_annotations: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host_write%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                slaves:
                    slave1:
                        host:     "%database_host_read%"
                        port:     "%database_port%"
                        dbname:   "%database_name%"
                        user:     "%database_user%"
                        password: "%database_password%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

nelmio_cors:
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'OPTIONS']
            max_age: 3600

monolog:
    use_microseconds: false
    handlers:
        applog:
            type: fingers_crossed
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            handler: file
        file:
            type: stream
            level: error

lsw_memcache:
    doctrine:
        metadata_cache:
            pool: default
            entity_manager: default
            document_manager: default
        result_cache:
            pool: default
            entity_manager: [default, read]
            prefix: "result_"
        query_cache:
            pool: default
            entity_manager: default
    pools:
        default:
            servers:
              - { host: localhost, tcp_port: 11211 }