services:
  vulgar_detector.word.repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - VulgarDetectorBundle\Entity\Word

  vulgar_detector.detector.static_detector:
    class: VulgarDetectorBundle\Detector\StaticDetector
    arguments:
      - '@vulgar_detector.word.repository'

  vulgar_detector.detector.similar_detector:
    class: VulgarDetectorBundle\Detector\SimilarDetector
    arguments:
      - '@vulgar_detector.word.repository'
      - '%default_threshold%'

  vulgar_detector.detector.factory_detector:
    class: VulgarDetectorBundle\Detector\FactoryDetector
    arguments:
      - '@vulgar_detector.detector.static_detector'
      - '@vulgar_detector.detector.similar_detector'

  vulgar_detector.word_tokenizer:
    class: VulgarDetectorBundle\Tokenizer\WordTokenizer

  vulgar_detector.lowercase_normalizer:
    class: VulgarDetectorBundle\Normalizer\LowercaseNormalizer

  vulgar_detector.validator.language:
    class: ApiBundle\Validator\Constraints\LanguageValidator
    arguments:
          entityManager: "@vulgar_detector.word.repository"
    tags:
      - { name: validator.constraint_validator, alias: language_validate }