services:
  vulgar_detector.word.repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - VulgarDetectorBundle\Entity\Word

  vulgar_detector.service.statistic_service:
    class: VulgarDetectorBundle\Service\StatisticService
    arguments:
      - '@doctrine.orm.entity_manager'

  vulgar_detector.detector.static_strategy:
    class: VulgarDetectorBundle\Detector\Strategy\StaticStrategy
    arguments:
      - '@vulgar_detector.word.repository'
      - '@vulgar_detector.service.statistic_service'

  vulgar_detector.detector.strategy_factory:
    class: VulgarDetectorBundle\Detector\StrategyFactory
    arguments:
      - '@vulgar_detector.detector.static_strategy'

  vulgar_detector.corrector.vulgar_corrector:
    class: VulgarDetectorBundle\Corrector\VulgarCorrector
    arguments:
      - '@vulgar_detector.word.repository'


