services:
  vulgar_detector.word.repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - VulgarDetectorBundle\Entity\Word

  vulgar_detector.detector.static_detector:
    class: VulgarDetectorBundle\Detector\StaticDetector
    arguments:
      - '@vulgar_detector.word.repository'

  vulgar_detector.word_tokenizer:
    class: VulgarDetectorBundle\Tokenizer\WordTokenizer

  vulgar_detector.lowercase_normalizer:
    class: VulgarDetectorBundle\Normalizer\LowercaseNormalizer

