ApiBundle\Model\Query:
    properties:
        text:
            - NotBlank: ~
            - Length:
                max:   255
        language:
            - Length:
                max:   36
            - ApiBundle\Validator\Constraints\Language: ~