ApiBundle\Model\Query:
    properties:
        text:
            - NotBlank: ~
            - Length:
                max:   255
        output:
            - Choice:
                choices:  [simple, complex]
        threshold:
            - Range:
                min: 0
                max: 1
        language:
            - Length:
                max:   36
