VulgarDetectorBundle\Entity\Statistic:
    type: entity
    table: statistic
    repositoryClass: VulgarDetectorBundle\Repository\StatisticRepository
    id:
        key:
            column: _key
            type: string
            nullable: false
    fields:
        name:
            column: name
            type: string
            nullable: false
            length: 64
        value:
            column: value
            type: string
            nullable: false
            length: 64

    lifecycleCallbacks: {  }