VulgarDetectorBundle\Entity\Word:
    type: entity
    table: word
    repositoryClass: VulgarDetectorBundle\Repository\WordRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            column: name
            type: string
            nullable: false
            unique: true
            length: 255
        language:
            column: language
            type: string
            nullable: false
            length: 32

    lifecycleCallbacks: {  }