VulgarDetectorBundle\Entity\Word:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      groups: [WORD_DETAILS]
    value:
      expose: true
      groups: [WORD_DETAILS]
    language:
      expose: true
      groups: [WORD_DETAILS]
    type:
      expose: true
      groups: [WORD_DETAILS]